# Generated by Django 4.0.5 on 2023-12-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=45, unique=True, verbose_name='Modelo avión')),
                ('capacity', models.IntegerField(default=140, verbose_name='Capacidad avión')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Código de vuelo')),
                ('origin', models.CharField(choices=[('Santiago', 'SAN-CHI'), ('Lima', 'LIM-PER'), ('Buenos Aires', 'BAS-ARG'), ('La Paz', 'LPZ-BOL'), ('Quito', 'QUI-ECU')], default='SAN-CHI', max_length=45, verbose_name='Origen de vuelo')),
                ('destination', models.CharField(choices=[('Santiago', 'SAN-CHI'), ('Lima', 'LIM-PER'), ('Buenos Aires', 'BAS-ARG'), ('La Paz', 'LPZ-BOL'), ('Quito', 'QUI-ECU')], max_length=45, verbose_name='Destino de viaje')),
                ('flight_date', models.DateTimeField(verbose_name='Fecha de vuelo')),
                ('current_city', models.CharField(max_length=45, verbose_name='Ciudad actual')),
                ('state', models.CharField(choices=[('Agendado', 'Agendado'), ('Completado', 'Completado')], default='Agendado', max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('planes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.plane', verbose_name='Id avión')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='Nombre pasajero')),
                ('rut', models.CharField(max_length=45, verbose_name='RUT')),
                ('vaccine', models.CharField(choices=[('Sinovac', 'Sinovac'), ('Pfizer', 'Pfizer'), ('Cancino', 'Cancino'), ('Astrazéneca', 'Astrazéneca'), ('Otra', 'Otra')], max_length=45, verbose_name='Esquema vacunación')),
                ('birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('travels_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.travel', verbose_name='Id vuelo')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['-created'],
            },
        ),
    ]
