# Generated by Django 4.0.5 on 2023-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_alter_plane_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='travels_id',
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(choices=[('Santiago', 'Santiago - Chile'), ('Lima', 'Lima - Perú'), ('Buenos Aires', 'Buenos Aires - Argentina'), ('La Paz', 'La Paz - Bolivia'), ('Quito', 'Quito - Ecuador')], max_length=45, verbose_name='Destino de viaje'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='origin',
            field=models.CharField(choices=[('Santiago', 'Santiago - Chile'), ('Lima', 'Lima - Perú'), ('Buenos Aires', 'Buenos Aires - Argentina'), ('La Paz', 'La Paz - Bolivia'), ('Quito', 'Quito - Ecuador')], default='SAN-CHI', max_length=45, verbose_name='Origen de vuelo'),
        ),
    ]
