# Generated by Django 4.0.5 on 2023-12-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_alter_travel_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='travels_id',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='corpus.travel', verbose_name='Id vuelo'),
            preserve_default=False,
        ),
    ]
