# Generated by Django 4.0.5 on 2023-12-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_passenger_travels_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(choices=[('Santiago', 'Santiago - Chile'), ('Lima', 'Lima - Perú'), ('Buenos Aires', 'Buenos Aires - Argentina'), ('La Paz', 'La Paz - Bolivia'), ('Quito', 'Quito - Ecuador')], default='Seleccione destino', max_length=45, verbose_name='Destino de viaje'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='origin',
            field=models.CharField(choices=[('Santiago', 'Santiago - Chile'), ('Lima', 'Lima - Perú'), ('Buenos Aires', 'Buenos Aires - Argentina'), ('La Paz', 'La Paz - Bolivia'), ('Quito', 'Quito - Ecuador')], default='Seleccione origen', max_length=45, verbose_name='Origen de vuelo'),
        ),
    ]
