# Generated by Django 4.0.5 on 2023-12-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
