# Generated by Django 4.0.5 on 2023-12-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
