# Generated by Django 4.0.5 on 2023-12-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(choices=[('Santiago', 'SAN-CHI'), ('Lima', 'LIM-PER'), ('Buenos Aires', 'BAS-ARG'), ('La Paz', 'LPZ-BOL'), ('Quito', 'QUI-ECU')], max_length=45, verbose_name='Destino de viaje'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='origin',
            field=models.CharField(choices=[('Santiago', 'SAN-CHI'), ('Lima', 'LIM-PER'), ('Buenos Aires', 'BAS-ARG'), ('La Paz', 'LPZ-BOL'), ('Quito', 'QUI-ECU')], default='SAN-CHI', max_length=45, verbose_name='Origen de vuelo'),
        ),
    ]
